from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

# 添加项目根目录到路径
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config_loader import load_config

_config = load_config()

# 数据与配置文件都落在本包目录下
_PKG_DIR = Path(__file__).resolve().parent
_DEFAULT_DATA_DIR = _PKG_DIR / "redis_data"
_CONF_NAME = "redis_local.conf"


def _data_dir() -> Path:
    override = _config.redis.local_data_dir
    if override:
        return Path(override).resolve()
    return _DEFAULT_DATA_DIR.resolve()


def _redis_server_binary() -> str | None:
    env_bin = _config.redis.server_bin
    if env_bin:
        return env_bin if Path(env_bin).is_file() or shutil.which(env_bin) else None
    return shutil.which("redis-server")


def write_local_redis_conf(
    data_dir: Path,
    port: int,
    bind: str = "127.0.0.1",
) -> Path:
    """写入最小配置并返回配置文件路径。"""
    data_dir.mkdir(parents=True, exist_ok=True)
    conf_path = data_dir / _CONF_NAME
    # dir 必须为绝对路径；仅监听本机降低误暴露风险
    text = f"""# auto-generated by history_redis.run_local_redis — do not hand-edit blindly
bind {bind}
port {port}
protected-mode yes
daemonize no
dir {data_dir.as_posix()}
dbfilename dump.rdb
appendonly yes
appendfilename "appendonly.aof"
"""
    conf_path.write_text(text, encoding="utf-8")
    return conf_path


def run_local_redis(
    port: int | None = None,
    bind: str | None = None,
    redis_server: str | None = None,
) -> int:
    port = port if port is not None else _config.ports.redis_local
    bind = bind if bind is not None else _config.redis.local_bind
    data_dir = _data_dir()
    binary = redis_server or _redis_server_binary()
    if not binary:
        sys.stderr.write(
            "找不到 redis-server。请安装 Redis 服务端或设置环境变量 REDIS_SERVER_BIN。\n"
            "示例（Ubuntu/WSL）：sudo apt-get install -y redis-server\n"
        )
        return 127

    conf = write_local_redis_conf(data_dir, port=port, bind=bind)
    sys.stderr.write(
        f"启动 Redis：{binary}\n"
        f"  配置：{conf}\n"
        f"  数据目录（RDB/AOF）：{data_dir}\n"
        f"  连接 URL：redis://{bind}:{port}/0\n"
        "按 Ctrl+C 停止。\n"
    )
    try:
        return subprocess.call([binary, str(conf)])
    except KeyboardInterrupt:
        return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="在 history_redis/redis_data 下持久化并前台启动 redis-server")
    p.add_argument("--port", type=int, default=None, help=f"默认 {_config.ports.redis_local}")
    p.add_argument("--bind", default=None, help=f"默认 {_config.redis.local_bind}")
    p.add_argument("--redis-server", dest="redis_server", default=None, help="redis-server 可执行文件路径")
    args = p.parse_args(argv)
    
    bind = args.bind if args.bind is not None else _config.redis.local_bind
    return run_local_redis(port=args.port, bind=bind, redis_server=args.redis_server)


if __name__ == "__main__":
    raise SystemExit(main())
